### PR TITLE
Little error in example code

### PR DESCRIPTION
**Pull request by Gilles86**
mu_g instead of mu_group

### CODE REVIEW

**Comment by twiecki** [comment]
Thanks!

**Comment by twiecki** [comment]
@Gilles86 Are you using kabuki? Would be interested to hear more about your application.

**Comment by Gilles86** [comment]
Hey @twiecki,

Yes, I have used it quite a bit. It can be a very powerful tool! So far I have used it for 1) learning about graphical Bayesian models in general 2) fitting a stop signal version of the LBA model and 3) fitting hemodynamic response functions to fMRI data. Especially the HRF project seems to work very well. The LBA model is just very tricky to fit, let alone a stop signal version of it.

The problem I have with Kabuki is the pymc-backend: it's all built so generalized and object-oriented that it becomes hard to understand for someone who was not involved in the development. I wanted to implement the differential evolution MCMC algorithm within its framework, but it was just too hard for me, especially as I want to be able to parallelize it. The past week I basically wrote my own very lightweight Bayesian graphical models engine. I guess that's a no-go from an engineering perspective, but it was quite fun and I learned a lot:
https://github.com/Gilles86/flogiston

Maybe it would be nice to get in contact some time to talk about implementing the DE MCMC sampler in pymc? It must be possible.. 

Are you actually still in Michael Frank's lab? I saw the JoN-paper: pretty impressive (although I have some problems with some of its claims ;)).

Cheers,
Gilles

**Comment by Gilles86** [comment]
(DE MCMC: Turner, B. M., Sederberg, P. B., Brown, S. D., & Steyvers, M. (2013). A method for efficiently sampling from distributions with correlated dimensions. Psychological Methods, 18(3), 368–384. doi:10.1037/a0032222)

**Comment by twiecki** [comment]
Cool, thanks for the background! You might be interested in [pymc3](https://github.com/pymc-devs/pymc) which has a much better design.

**Pull request merged**
